# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170228_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='yayinlanma_tarihi',
            new_name='yayinlama_tarihi',
        ),
        migrations.AlterField(
            model_name='post',
            name='yaratilis_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 21, 2, 26, 847319, tzinfo=utc)),
        ),
    ]
