# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170228_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='yayinlama_tarihi',
            new_name='yayin_tarihi',
        ),
        migrations.AlterField(
            model_name='post',
            name='yaratilis_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 21, 15, 47, 969090, tzinfo=utc)),
        ),
    ]
