# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170228_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='yaratilis_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 21, 16, 0, 673763, tzinfo=utc)),
        ),
    ]
