# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:41
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170301_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 2, 16, 41, 11, 372893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='yaratilis_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 2, 16, 41, 11, 370891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='yazi',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
